name: myterraform
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_KEY }}
  
  
jobs:
 terrafom-workflow:
  permissions:
   contents: write
   issues: write
   pull-requests: write
  runs-on: ubuntu-latest
  steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.1.9
    - name: Terraform format
      run: terraform fmt -check
    - name: Terraform init
      run: terraform init
    - name: Terraform validate
      run: terraform validate
    - name: Terraform plan
      run: terraform plan
     
    - name: release
      run: docker run --rm -v "$(pwd):/app" -w /app node:16 /c/Users/donne/Music/actions/sementic/run-semantic-release.sh
      env:
       GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}


       
